# ~/.starship.config.toml
# Note, requires a nerd font to be installed

add_newline = false
format = """$character $directory"""
right_format = """$all"""

[aws]
disabled = true

[battery]
disabled = false
# Defaults are , , , , 

[[battery.display]]
threshold = 50
style = "red"

[character]
success_symbol = "[->](bold green)"
error_symbol = "[ ](bold red)"

[cmake]
disabled = true

[cobol]
disabled = true

[cmd_duration]
disabled = true

[crystal]
disabled = true

[dart]
disabled = true

[deno]
disabled = true

[directory]
truncation_length = 1
truncate_to_repo = false
read_only = "  "
read_only_style = "red"
truncation_symbol = ""
home_symbol = "~"
style="bold blue"
format = "[$path]($style)[$read_only]($read_only_style) "

[docker_context]
disabled = true

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[env_var]
disabled = true

[erlang]
disabled = true

[fill]
disabled = true

[gcloud]
disabled = true

[git_branch]
disabled = false
format = " [$symbol$branch]($style) "
always_show_remote = false
symbol = " "
style = "bold purple"
only_attached = "true"

[git_commit]
disabled = true

[git_state]
disabled = false
# defaults for now, might fix this later

[git_metrics]
disabled = true

[git_status]
disabled = false
format = '([\[$all_status$ahead_behind\]]($style) )'
conflicted = "✗"
ahead = "⇡"
behind = "⇣"
diverged = "✂"
up_to_date = ""
untracked = "✱"
stashed = "✭"
modified = "✈"
staged = "+"
renamed = "➦"
style = "bold cyan"

[golang]
disabled = true

[helm]
disabled = true

[hostname]
disabled = false
ssh_only = true
format =  "on [$hostname](bold yellow) "
trim_at = ".ucsc.edu"

[java]
disabled = true

[jobs]
disabled = false
symbol_threshold = 1
style = "white bold"

[julia]
disabled = true

[kotlin]
disabled = true

[kubernetes]
disabled = true

[line_break]
disabled = false

[lua]
disabled = true

[memory_usage]
disabled = false
threshold = 60
symbol = " "
format = " $symbol  ${ram}($style) "

[hg_branch]
disabled = true

[nim]
disabled = true

[nix_shell]
disabled = true

[nodejs]
disabled = true

[ocaml]
disabled = true

[openstack]
disabled = true

[package]
disabled = true

[perl]
disabled = true

[php]
disabled = true

[purescript]
disabled = true

[python]
disabled = true

[rlang]
disabled = true

[red]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

[scala]
disabled = true

[shell]
disabled = true
# this might be cool if you decide to switch between bash/fish/zsh etc

[shlvl]
disabled = true

[singularity]
disabled = true

[status]
disabled = true
# add the back eventually

[swift]
disabled = true

[terraform]
disabled = true

[time]
disabled = true 
use_12hr = true
style = "bold yellow"
format = " [$time]($style) "

[username]
disabled = true
# would be cool for DO droplet with multiple users

[vagrant]
disabled = true

[vlang]
disabled = true

[vcsh]
disabled = true

[zig]
disabled = true
